//******************************************************************
// 
//  Generated by IDL to C++ Translator
//  
//  File name: Chat.cpp
//  Source: ../../idl/Chat.idl
//  Generated: Sat Feb 11 14:25:53 2017
//  OpenSplice V6.4.140407OSS
//  
//******************************************************************

#include "Chat.h"




