//******************************************************************
// 
//  Generated by IDL to C++ Translator
//  
//  File name: HelloWorldData.cpp
//  Source: ../../idl/HelloWorldData.idl
//  Generated: Fri Mar 24 14:25:59 2017
//  OpenSplice V6.4.140407OSS
//  
//******************************************************************

#include "HelloWorldData.h"




